### ISSUE TITLE
Flags type problem in last telegram schema 

### ISSUE THREAD

**Issue by mahdiit** [everbytes/SharpTL#5]
latest telegram schema json contains flag that can not be serialized with this compiler

```
[TLObject(0x818426CD)]
    public partial class PeerSettings : IPeerSettings
    {
        [TLProperty(1)]
        public I# Flags { get; set; }

        [TLProperty(2)]
        public IFlags0?true ReportSpam { get; set; }

    }
how it 
```
can be fixed? any solution?

definition: 
`"params":[{"name":"flags","type":"#"},{"name":"report_spam","type":"flags.0?true"}],"type":"PeerSettings"}`

**Comment by intagger** [comment]
This issue doesn't target this project.
